name: Deploy docs
'on':
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
        env:
          TURBO_TOKEN: ymaK3d2lrXGzcerDAV0XYH8i
          TURBO_TEAM: adriano-kleins-projects
      - name: Deploy storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: '${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}'
